apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-share-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: db-local
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /media/share/database/mysql
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-share-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: db-local
  volumeName: mysql-share-pv