# pv-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path     # 또는 nfs-sc, gp2 등
  hostPath:
    path: /data/postgres           # Docker Desktop 호스트 경로
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pvc
  namespace: song-test                  # 차트가 배포될 네임스페이스
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
